apiVersion: v1
kind: ConfigMap
metadata:
  name: dmart-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dmart.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
