apiVersion: v1
kind: Secret
metadata:
  name: dmart-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dmart.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.secretEnv }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
