apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: dmart-repo
  namespace: flux-system
spec:
  interval: 5m
  url: https://github.com/rooselvelt6/dmart.git
  ref:
    branch: main
